# config/rules.yaml
rules:
  - name: sql_injection
    sources:
      - pattern: "$_GET[*]"
      - pattern: "$_POST[*]"
      - pattern: "$_REQUEST[*]"
    sinks:
      - function: "mysqli_query"
        args:
          - index: 1
            type: string
            contains: variable
        vuln: "sql_injection"
      - function: "mysql_query"
        args:
          - index: 0
            type: string
            contains: variable
        vuln: "sql_injection"
    filters:
      - function: "mysqli_real_escape_string"
        sanitizes: [ "sql_injection" ]
      - function: "filter_var"
        sanitizes: [ "sql_injection" ]

  - name: xss
    sources:
      - pattern: "$_GET[*]"
      - pattern: "$_POST[*]"
    sinks:
      - function: "echo"
        args:
          - index: 0
            type: variable
        vuln: "xss"
      - function: "print"
        args:
          - index: 0
            type: variable
        vuln: "xss"
    filters:
      - function: "htmlspecialchars"
        sanitizes: [ "xss" ]
      - function: "htmlentities"
        sanitizes: [ "xss" ]

  - name: auth_bypass
    patterns:
      - type: binary_expression
        operator: "=="
        vuln: "auth_bypass"